### ISSUE TITLE
chrome 66版本后会提示一个错误：需要与用户交互才能被播放

### ISSUE THREAD

**Issue by thunderstreak** [HTML50/audioVisualizer#2]
Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first.

**Comment by HTML50** [comment]
@thunderstreak 66版本的新安全策略。需要交互一下才能播放音频（比如加个播放按钮）

**Comment by MLuminary** [comment]
点击后 调用 `context.resume()`
